// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal_proto.proto

public final class AnimalProto {
  private AnimalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ZooOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Animal animals = 1;
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    java.util.List<Animal>
        getAnimalsList();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    Animal getAnimals(int index);
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    int getAnimalsCount();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    AnimalOrBuilder getAnimalsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Zoo}
   */
  public static final class Zoo extends
      com.google.protobuf.GeneratedMessage
      implements ZooOrBuilder {
    // Use Zoo.newBuilder() to construct.
    private Zoo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Zoo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Zoo defaultInstance;
    public static Zoo getDefaultInstance() {
      return defaultInstance;
    }

    public Zoo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Zoo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                animals_ = new java.util.ArrayList<Animal>();
                mutable_bitField0_ |= 0x00000001;
              }
              animals_.add(input.readMessage(Animal.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          animals_ = java.util.Collections.unmodifiableList(animals_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimalProto.internal_static_Zoo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimalProto.internal_static_Zoo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Zoo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Zoo> PARSER =
        new com.google.protobuf.AbstractParser<Zoo>() {
      public Zoo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Zoo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Zoo> getParserForType() {
      return PARSER;
    }

    // repeated .Animal animals = 1;
    public static final int ANIMALS_FIELD_NUMBER = 1;
    private java.util.List<Animal> animals_;
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public java.util.List<Animal> getAnimalsList() {
      return animals_;
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList() {
      return animals_;
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public int getAnimalsCount() {
      return animals_.size();
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public Animal getAnimals(int index) {
      return animals_.get(index);
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public AnimalOrBuilder getAnimalsOrBuilder(
        int index) {
      return animals_.get(index);
    }

    private void initFields() {
      animals_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAnimalsCount(); i++) {
        if (!getAnimals(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < animals_.size(); i++) {
        output.writeMessage(1, animals_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < animals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, animals_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Zoo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Zoo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Zoo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Zoo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Zoo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Zoo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Zoo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Zoo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Zoo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Zoo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Zoo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Zoo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ZooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimalProto.internal_static_Zoo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimalProto.internal_static_Zoo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Zoo.class, Builder.class);
      }

      // Construct using AnimalProto.Zoo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAnimalsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimalProto.internal_static_Zoo_descriptor;
      }

      public Zoo getDefaultInstanceForType() {
        return Zoo.getDefaultInstance();
      }

      public Zoo build() {
        Zoo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Zoo buildPartial() {
        Zoo result = new Zoo(this);
        int from_bitField0_ = bitField0_;
        if (animalsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            animals_ = java.util.Collections.unmodifiableList(animals_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.animals_ = animals_;
        } else {
          result.animals_ = animalsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Zoo) {
          return mergeFrom((Zoo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Zoo other) {
        if (other == Zoo.getDefaultInstance()) return this;
        if (animalsBuilder_ == null) {
          if (!other.animals_.isEmpty()) {
            if (animals_.isEmpty()) {
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAnimalsIsMutable();
              animals_.addAll(other.animals_);
            }
            onChanged();
          }
        } else {
          if (!other.animals_.isEmpty()) {
            if (animalsBuilder_.isEmpty()) {
              animalsBuilder_.dispose();
              animalsBuilder_ = null;
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000001);
              animalsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAnimalsFieldBuilder() : null;
            } else {
              animalsBuilder_.addAllMessages(other.animals_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAnimalsCount(); i++) {
          if (!getAnimals(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Zoo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Zoo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Animal animals = 1;
      private java.util.List<Animal> animals_ =
        java.util.Collections.emptyList();
      private void ensureAnimalsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          animals_ = new java.util.ArrayList<Animal>(animals_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Animal, Animal.Builder, AnimalOrBuilder> animalsBuilder_;

      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<Animal> getAnimalsList() {
        if (animalsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(animals_);
        } else {
          return animalsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public int getAnimalsCount() {
        if (animalsBuilder_ == null) {
          return animals_.size();
        } else {
          return animalsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal getAnimals(int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);
        } else {
          return animalsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder setAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.set(index, value);
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder setAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.set(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(index, value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAllAnimals(
          Iterable<? extends Animal> values) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          super.addAll(values, animals_);
          onChanged();
        } else {
          animalsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder clearAnimals() {
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder removeAnimals(int index) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.remove(index);
          onChanged();
        } else {
          animalsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder getAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public AnimalOrBuilder getAnimalsOrBuilder(
          int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);  } else {
          return animalsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<? extends AnimalOrBuilder>
           getAnimalsOrBuilderList() {
        if (animalsBuilder_ != null) {
          return animalsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(animals_);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder addAnimalsBuilder() {
        return getAnimalsFieldBuilder().addBuilder(
            Animal.getDefaultInstance());
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder addAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().addBuilder(
            index, Animal.getDefaultInstance());
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<Animal.Builder>
           getAnimalsBuilderList() {
        return getAnimalsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Animal, Animal.Builder, AnimalOrBuilder>
          getAnimalsFieldBuilder() {
        if (animalsBuilder_ == null) {
          animalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Animal, Animal.Builder, AnimalOrBuilder>(
                  animals_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          animals_ = null;
        }
        return animalsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Zoo)
    }

    static {
      defaultInstance = new Zoo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Zoo)
  }

  public interface AnimalOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Animal> {

    // required .Animal.Type type = 1;
    /**
     * <code>required .Animal.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .Animal.Type type = 1;</code>
     */
    Animal.Type getType();
  }
  /**
   * Protobuf type {@code Animal}
   */
  public static final class Animal extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Animal> implements AnimalOrBuilder {
    // Use Animal.newBuilder() to construct.
    private Animal(ExtendableBuilder<Animal, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Animal(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Animal defaultInstance;
    public static Animal getDefaultInstance() {
      return defaultInstance;
    }

    public Animal getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Animal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimalProto.internal_static_Animal_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimalProto.internal_static_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Animal.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Animal> PARSER =
        new com.google.protobuf.AbstractParser<Animal>() {
      public Animal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Animal(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Animal> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Animal.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Cat = 1;</code>
       */
      Cat(0, 1),
      /**
       * <code>Dog = 2;</code>
       */
      Dog(1, 2),
      ;

      /**
       * <code>Cat = 1;</code>
       */
      public static final int Cat_VALUE = 1;
      /**
       * <code>Dog = 2;</code>
       */
      public static final int Dog_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return Cat;
          case 2: return Dog;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Animal.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Animal.Type)
    }

    private int bitField0_;
    // required .Animal.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private Type type_;
    /**
     * <code>required .Animal.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Animal.Type type = 1;</code>
     */
    public Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = Type.Cat;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Animal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Animal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Animal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Animal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Animal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Animal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Animal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Animal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Animal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Animal}
     */
    public static final class Builder extends
        ExtendableBuilder<
          Animal, Builder> implements AnimalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimalProto.internal_static_Animal_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimalProto.internal_static_Animal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Animal.class, Builder.class);
      }

      // Construct using AnimalProto.Animal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = Type.Cat;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimalProto.internal_static_Animal_descriptor;
      }

      public Animal getDefaultInstanceForType() {
        return Animal.getDefaultInstance();
      }

      public Animal build() {
        Animal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Animal buildPartial() {
        Animal result = new Animal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Animal) {
          return mergeFrom((Animal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Animal other) {
        if (other == Animal.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Animal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Animal) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Animal.Type type = 1;
      private Type type_ = Type.Cat;
      /**
       * <code>required .Animal.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Animal.Type type = 1;</code>
       */
      public Type getType() {
        return type_;
      }
      /**
       * <code>required .Animal.Type type = 1;</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Animal.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = Type.Cat;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Animal)
    }

    static {
      defaultInstance = new Animal(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Animal)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Zoo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Zoo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Animal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Animal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022animal_proto.proto\"\037\n\003Zoo\022\030\n\007animals\030\001" +
      " \003(\0132\007.Animal\"H\n\006Animal\022\032\n\004type\030\001 \002(\0162\014." +
      "Animal.Type\"\030\n\004Type\022\007\n\003Cat\020\001\022\007\n\003Dog\020\002*\010\010" +
      "d\020\200\200\200\200\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Zoo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Zoo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Zoo_descriptor,
              new String[] { "Animals", });
          internal_static_Animal_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Animal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Animal_descriptor,
              new String[] { "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
