// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dog_proto.proto

public final class DogProto {
  private DogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(Dog.animal);
  }
  public interface DogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 bones_buried = 1;
    /**
     * <code>optional uint32 bones_buried = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    boolean hasBonesBuried();
    /**
     * <code>optional uint32 bones_buried = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    int getBonesBuried();
  }
  /**
   * Protobuf type {@code Dog}
   */
  public static final class Dog extends
      com.google.protobuf.GeneratedMessage
      implements DogOrBuilder {
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Dog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Dog defaultInstance;
    public static Dog getDefaultInstance() {
      return defaultInstance;
    }

    public Dog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bonesBuried_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DogProto.internal_static_Dog_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DogProto.internal_static_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dog.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Dog> PARSER =
        new com.google.protobuf.AbstractParser<Dog>() {
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 bones_buried = 1;
    public static final int BONES_BURIED_FIELD_NUMBER = 1;
    private int bonesBuried_;
    /**
     * <code>optional uint32 bones_buried = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public boolean hasBonesBuried() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 bones_buried = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public int getBonesBuried() {
      return bonesBuried_;
    }

    private void initFields() {
      bonesBuried_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, bonesBuried_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, bonesBuried_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Dog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DogProto.internal_static_Dog_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DogProto.internal_static_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dog.class, Builder.class);
      }

      // Construct using DogProto.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bonesBuried_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DogProto.internal_static_Dog_descriptor;
      }

      public Dog getDefaultInstanceForType() {
        return Dog.getDefaultInstance();
      }

      public Dog build() {
        Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Dog buildPartial() {
        Dog result = new Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bonesBuried_ = bonesBuried_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dog) {
          return mergeFrom((Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dog other) {
        if (other == Dog.getDefaultInstance()) return this;
        if (other.hasBonesBuried()) {
          setBonesBuried(other.getBonesBuried());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Dog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 bones_buried = 1;
      private int bonesBuried_ ;
      /**
       * <code>optional uint32 bones_buried = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public boolean hasBonesBuried() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 bones_buried = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public int getBonesBuried() {
        return bonesBuried_;
      }
      /**
       * <code>optional uint32 bones_buried = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder setBonesBuried(int value) {
        bitField0_ |= 0x00000001;
        bonesBuried_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 bones_buried = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder clearBonesBuried() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bonesBuried_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Dog)
    }

    static {
      defaultInstance = new Dog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Dog)
    public static final int ANIMAL_FIELD_NUMBER = 101;
    /**
     * <code>extend .Animal { ... }</code>
     */
    public static final
      GeneratedExtension<
        AnimalProto.Animal,
        Dog> animal = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          Dog.getDefaultInstance(),
          0,
          Dog.class,
          Dog.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Dog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Dog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017dog_proto.proto\032\022animal_proto.proto\":\n" +
      "\003Dog\022\024\n\014bones_buried\030\001 \001(\r2\035\n\006animal\022\007.A" +
      "nimal\030e \002(\0132\004.Dog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Dog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Dog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Dog_descriptor,
              new String[] { "BonesBuried", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AnimalProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
